### ISSUE TITLE
Return 500 instead of 400 for try catch block in Handler

### ISSUE THREAD

**Issue by nartc** [hieunc229/express-imgwiz#1]
https://github.com/hieunc229/express-imgwiz/blob/master/src/handlers/handler.ts#L42
It is more conformed with good practice to return a 5xx error instead of 4xx error because this is an unknown error that the `catch` block is trying to throw. Should be an `InternalServerException`

**Comment by hieunc229** [comment]
Hey @nartc, thanks for pointing out. I'll make an update :)

**Comment by hieunc229** [comment]
I've pushed an update with a correct server error code, also [added try/catch block for imgWizMiddleware ](https://github.com/hieunc229/express-imgwiz/commit/bf6e8d2a2c681056ee50a80ab4e0fc8e5c5a2141).
I'll close this thread and feel free to re-open or create a new issue. Thank again!
