### ISSUE TITLE
Unable fetch from png svg

### ISSUE THREAD

**Issue by sprabowo** [hieunc229/express-imgwiz#2]
Hi, 
i have problem with other image extension above, you can check this
https://wiz.saltar.co/photos/?url=https://geekflare.com/wp-content/uploads/2016/11/cloudflare-marketshare.png
https://wiz.saltar.co/photos/?url=https://github.com/hieunc229/express-imgwiz/raw/master/imgwiz.svg?sanitize=true

**Comment by hieunc229** [comment]
Hey @sprabowo, thanks for reporting the issue. Looking at the photo headers, the first photo seems like its actual format isn't `.png` but `.webp`. The second one is compressed as `gzip`.

They could be the reason, not entirely sure though. I'll have a look and let you know

**Comment by sprabowo** [comment]
Hi @hieunc229, thanks for the info. I'll check with another image url. I just random pick from random site.
